version: '2'

services:
   db:
     image: mysql:5.7
     ports:
      - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: reddymadedesign
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     build: .
     ports:
       - "8000:80"
     links:
       - db
     restart: always
     volumes:
       - .:/var/www/public
     working_dir: /var/www/public
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
       SHELL: bash
volumes:
    db_data: