<?php
/**
 * Head Links
 *
 * Remove any unwanted header links generated by default.
 *
 * @package Carbon
 * @subpackage Setup
 * @since 2.0.0
 */

function carbon_remove_head_links() {
    remove_action('wp_head', 'rsd_link');
    remove_action('wp_head', 'wlwmanifest_link');
    remove_action('wp_head', 'rel_canonical');
    remove_action('wp_head', 'start_post_rel_link');
    remove_action('wp_head', 'adjacent_posts_rel_link_wp_head');
    remove_action('wp_head', 'wp_generator');
    /* Remove two lines below to include Emoji support */
    remove_action('wp_head', 'print_emoji_detection_script', 7);
    remove_action('wp_print_styles', 'print_emoji_styles');
}
add_action('init', 'carbon_remove_head_links');
